# Copyright (C) 2018 Sebastian Pipping <sebastian@pipping.org>
# Licensed under GNU Affero GPL v3 or later

networks:
  ssl-reverse-proxy:
    external: yes

services:
  wnpp-debian-net:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      # KEEP IN SYNC with container "cron" below
      WDN_ALLOWED_HOSTS: ${WDN_ALLOWED_HOSTS}
      WDN_DEBUG: ${WDN_DEBUG}
      WDN_POSTGRES_HOST: postgres
      WDN_POSTGRES_NAME: ${WDN_POSTGRES_NAME:?}
      WDN_POSTGRES_PASSWORD: ${WDN_POSTGRES_PASSWORD:?}
      WDN_POSTGRES_PORT: 5432
      WDN_POSTGRES_USER: ${WDN_POSTGRES_USER:?}
      WDN_SECRET_KEY: ${WDN_SECRET_KEY:?}
      WDN_SENTRY_DSN: ${WDN_SENTRY_DSN}
      # KEEP IN SYNC with container "cron" below
    ports:
      - 127.0.0.1:51080:51080
    networks:
      - default
      - ssl-reverse-proxy
    user: 1001:1001
    cap_drop:
      - ALL
    restart: unless-stopped
    tty: true

  cron:
    depends_on:
      - postgres
    image: ${COMPOSE_PROJECT_NAME:-wnppdebiannet}_wnpp-debian-net
    command: ["sh", "-c", "supercronic -sentry-dsn \"${WDN_SENTRY_DSN}\" ~/crontab"]
    environment:
      # KEEP IN SYNC with container "django" above
      WDN_ALLOWED_HOSTS: ${WDN_ALLOWED_HOSTS}
      WDN_DEBUG: ${WDN_DEBUG}
      WDN_POSTGRES_HOST: postgres
      WDN_POSTGRES_NAME: ${WDN_POSTGRES_NAME:?}
      WDN_POSTGRES_PASSWORD: ${WDN_POSTGRES_PASSWORD:?}
      WDN_POSTGRES_PORT: 5432
      WDN_POSTGRES_USER: ${WDN_POSTGRES_USER:?}
      WDN_SECRET_KEY: ${WDN_SECRET_KEY:?}
      WDN_SENTRY_DSN: ${WDN_SENTRY_DSN}
      # KEEP IN SYNC with container "django" above
    networks:
      - default
    user: 1001:1001
    cap_drop:
      - ALL
    restart: unless-stopped
    tty: true

  postgres:
    image: postgres:15.2  # due to postgresql-client version 15.2 in Alpine 3.17
    volumes:
      - ~/wnpp-debian-net/postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${WDN_POSTGRES_USER:?}
      POSTGRES_PASSWORD: ${WDN_POSTGRES_PASSWORD:?}
      POSTGRES_DB: ${WDN_POSTGRES_NAME:?}
    logging:
      driver: 'none'
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_READ_SEARCH
      - FOWNER
      - SETGID
      - SETUID
    restart: unless-stopped
