# Generated by Django 3.1.6 on 2021-02-17 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wnpp_debian_net', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debianwnpp',
            name='has_smaller_sibling',
            field=models.BooleanField(default=False),
        ),
    ]
